# Generated by Django 3.1.4 on 2020-12-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cipher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название шифра')),
                ('class_name', models.CharField(max_length=128, verbose_name='Имя класса')),
                ('is_asymmetric', models.BooleanField(choices=[(False, 'Симметричный'), (True, 'Ассиметричный')], verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='CipherKeyLengths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.SmallIntegerField(choices=[(64, '64'), (128, '128'), (256, '256'), (512, '512')], verbose_name='Длинна ключа')),
            ],
        ),
        migrations.CreateModel(
            name='SymmetricCryptographyObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название объекта')),
                ('is_file', models.BooleanField()),
                ('secret_key', models.TextField(verbose_name='Секретный ключ')),
                ('cipher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.cipher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cipher',
            name='key_lengths',
            field=models.ManyToManyField(to='main.CipherKeyLengths'),
        ),
        migrations.CreateModel(
            name='AsymmetricCryptographyObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название объекта')),
                ('is_file', models.BooleanField()),
                ('private_key', models.TextField(verbose_name='Закрытый ключ')),
                ('public_key', models.TextField(verbose_name='Открытый ключ')),
                ('cipher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.cipher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
