# Generated by Django 3.1.4 on 2020-12-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CipherKeyLengths',
            new_name='CipherKeyLength',
        ),
    ]
