# Generated by Django 3.1.4 on 2020-12-09 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201208_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='CipherKeyLengthRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.cipher')),
                ('cipher_key_length', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.cipherkeylength')),
            ],
        ),
        migrations.RemoveField(
            model_name='cipher',
            name='key_lengths',
        ),
        migrations.AddField(
            model_name='cipher',
            name='key_lengths',
            field=models.ManyToManyField(through='main.CipherKeyLengthRelation', to='main.CipherKeyLength'),
        ),
    ]
