# Generated by Django 3.1.4 on 2020-12-10 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201209_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asymmetriccryptographyobject',
            name='cipher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.cipher'),
        ),
        migrations.AlterField(
            model_name='asymmetriccryptographyobject',
            name='key_length',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main.cipherkeylengthrelation'),
        ),
        migrations.AlterField(
            model_name='cipherkeylength',
            name='length',
            field=models.SmallIntegerField(choices=[(0, 'Любая'), (64, '64'), (128, '128'), (256, '256'), (512, '512')], default=0, verbose_name='Длинна ключа'),
        ),
        migrations.AlterField(
            model_name='symmetriccryptographyobject',
            name='cipher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.cipher'),
        ),
        migrations.AlterField(
            model_name='symmetriccryptographyobject',
            name='key_length',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main.cipherkeylengthrelation'),
        ),
    ]
