# Generated by Django 3.1.4 on 2020-12-10 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0005_auto_20201210_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='asymmetriccryptographyobject',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_main.asymmetriccryptographyobject_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='symmetriccryptographyobject',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_main.symmetriccryptographyobject_set+', to='contenttypes.contenttype'),
        ),
    ]
