# Generated by Django 3.1.4 on 2020-12-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201210_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asymmetriccryptographyobject',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='symmetriccryptographyobject',
            name='polymorphic_ctype',
        ),
    ]
