# Generated by Django 3.1.4 on 2020-12-11 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201210_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptographyObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название объекта')),
                ('private_key', models.TextField(verbose_name='Закрытый ключ')),
                ('public_key', models.TextField(verbose_name='Открытый ключ')),
                ('is_file', models.BooleanField()),
                ('cipher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.cipher')),
                ('key_length', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main.cipherkeylengthrelation')),
            ],
        ),
        migrations.RemoveField(
            model_name='symmetriccryptographyobject',
            name='cipher',
        ),
        migrations.RemoveField(
            model_name='symmetriccryptographyobject',
            name='key_length',
        ),
        migrations.DeleteModel(
            name='AsymmetricCryptographyObject',
        ),
        migrations.DeleteModel(
            name='SymmetricCryptographyObject',
        ),
    ]
