# Generated by Django 3.1.4 on 2020-12-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201217_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptographyobject',
            name='is_file',
        ),
    ]
