# Generated by Django 3.1.4 on 2020-12-17 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_load_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptographyobject',
            name='cipher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.cipher', verbose_name='Шифр'),
        ),
        migrations.AlterField(
            model_name='cryptographyobject',
            name='is_file',
            field=models.BooleanField(default=False, verbose_name='Из файла'),
        ),
        migrations.AlterField(
            model_name='cryptographyobject',
            name='key_length',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main.cipherkeylengthrelation', verbose_name='Длина ключа'),
        ),
        migrations.AlterField(
            model_name='cryptographyobject',
            name='public_key',
            field=models.TextField(blank=True, null=True, verbose_name='Открытый ключ'),
        ),
    ]
