# Generated by Django 3.1.4 on 2020-12-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_cryptographyobject_is_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptographyobject',
            name='key_length',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.cipherkeylengthrelation', verbose_name='Длина ключа'),
        ),
    ]
