# Generated by Django 3.1.4 on 2020-12-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201224_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cipher',
            name='class_name',
        ),
    ]
